# Thank you very much for downloading my resource!
# I would really appreciate a review on SpigotMC.org!

# Select your language:
# We currently support English (en) and German (de)
language: 'en'

# Are we allowed to automatically check for updates?
check_for_updates: true

# You can use this Symbol in front of your message insted of /tc to send a message into the TeamChat:
chat_symbol: '!'

# Permissions
# With this permission, a user is able to use the main functions of the TeamChat - /tc, /tc login, /tc logout
permission_use_teamchat: 'tc.use'

# With this permission, a user can list everyone who is currently logged in to the TeamChat:
permission_list: 'tc.list'

# With this permission, a user can toggle the TeamChat:
permission_toggle: 'tc.toggle'

# With this permission, a user will be automatically logged in when he enters the Network:
permission_autologin: 'tc.autologin'

# With this permission, a user is able to enter the GhostMode:
permission_ghostmode: 'tc.ghost'

# With this permission, a user will enter the GhostMode when he joins.
permission_autoghostmode: 'tc.autoghostmode'

# With this permission, a user can reload the Configuration of the Plugin:
permission_reload: 'tc.reload'

# With this permission, a user will get a message when a new Update for the Plugin is available:
permission_update: 'tc.update'